/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DISTSYS_H_RPCGEN
#define _DISTSYS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DIST_SYS_PROG 0x30000824
#define DIST_SYS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DISTSYS 1
extern  int * distsys_1(char **, CLIENT *);
extern  int * distsys_1_svc(char **, struct svc_req *);
extern int dist_sys_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DISTSYS 1
extern  int * distsys_1();
extern  int * distsys_1_svc();
extern int dist_sys_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DISTSYS_H_RPCGEN */
