// Monica Ovalekar	NetId: mso269	N#: N12316668
// processor.c
/* receiver.c takes input from the user.
If the input has the secret code "C00L", remote procedure is called
remote procedure takes the line of data counts its digits and dumps the data (alongwith the codeword) and the count (which does not include the two zeroes of the code word) in the file secrets.out
*/

#include <stdio.h>
#include <string.h>
#include "distsys.h" // distsys.h is generated by rpcgen

int * distsys_1_svc(char **distsys, struct svc_req *req)
{
    static int res; // since it is not multithreading or auto
    FILE *secrets;
	char *d;
    int n;

    secrets = fopen("secret.out", "a");

    if (secrets == (FILE *)NULL)    // if file is not opened
    {
        res = 0;
        return (&res);
    }

	printf("input received: %s",*distsys);

    // to count number of digits
	for (d = *distsys, n = 0; *d != '\0'; d++)
	{
		if (*d=='0' || *d=='1' || *d=='2' || *d=='3' || *d=='4' || *d=='5' || *d=='6' || *d=='7' || *d=='8' || *d=='9')
		{
			n++;	// for digit count
		}
	}

    fprintf(secrets, "%d is/are the number of digits in this string %s", n-2, *distsys);
    fclose(secrets);
    res = 1; // rpc was successful
    return (&res);
}