// Monica Ovalekar	NetId: mso269	N#: N12316668
// receiver.c
/* receiver.c takes input from the user.
If the input has the secret code "C00L", remote procedure is called
remote procedure takes the line of data counts its digits and dumps the data (alongwith the codeword) and the count (which does not include the two zeroes of the code word) in the file secrets.out
*/

#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <rpc/rpc.h>
#include "distsys.h"  // distsys.h is generated by rpcgen

// it checks if input has the code "C00L", if it does it is passes to the remote server
char* receive(char *input, const char *code)
{
    if(strstr(input, code) != NULL)
    {
        return input;
    }
    else
    {
        return NULL;
    }
}

int main(int argc, char *argv[])
{
    CLIENT *cl;
    int *res;
    char *server;
    int a;

    // if 2 arguments are not passed
    if (argc != 2)
    {
        printf("2 arguments are not passed");
        exit(1);
    }

    //creating client
    cl = clnt_create(argv[1], DIST_SYS_PROG, DIST_SYS_VERS, "tcp");
    if (cl == NULL) // if client is not created
    {
        clnt_pcreateerror(argv[1]);
        exit(1);
    }

    // server is argv[1]
    server = argv[1];

    // infinite loop
    while(1)
    {
        char *input;
        size_t len = 0;
        sleep(3);

        printf("Enter an alphanumeric string and type exit to exit:");
        if((a = getline(&input, &len, stdin)) == -1)
        {
            clnt_destroy(cl);   // client is destroyed
            exit(0);
        }

        if(strcmp(input, "exit\n") == 0)    // if exit is entered, break from the loop
        {
            clnt_destroy(cl);
            exit(0);
        }

        if(receive(input, "C00L")!= NULL)   // if receive has the C00L code then remote prcedure is called
        {
            res = distsys_1(&input, cl);    // remote procedure is given the address and client

            if (res == (int *)NULL) // remote procedure was not called
            {
                clnt_perror(cl, server);
                clnt_destroy(cl);
                exit(3);
            }

            printf("Remote procedure called successfully\n");

            if (*res != 1)  // if res is 0 then input was not written to the file
            {
                clnt_perror(cl,argv[1]);
                clnt_destroy(cl);
                exit(4);
            }
        }
    }

    clnt_destroy(cl);   // client created is destroyed
    return 0;
}